/**
 * 
 */
package org.darkimport.omeglespy$z;


/**
 * An event generated by an omegle server from an event ping.
 * 
 * @author user
 * 
 */
class OmegleEvent {

	private final OmegleEventType	eventType;
	private final String[]			args;

	public OmegleEvent(final OmegleEventType eventType, final String[] args) {
		this.eventType = eventType;
		this.args = args;
	}

	/**
	 * @return the source
	 */
	public OmegleEventType getSource() {
		return eventType;
	}

	/**
	 * @return the args
	 */
	public String[] getArgs() {
		return args;
	}

}
